widok wysylanie wiadomosci
akai-org/lekarz pull request #66
Opened 2019-11-12 17:52 UTC by PatrykGrzegorek

2019-11-12 18:19 UTC, dwdzdc requested changes

2019-11-12 18:19 UTC, Gumkle commented on lekarz/templates/message/outbox.html
> +<!DOCTYPE html>
Tutaj templata

2019-11-12 18:19 UTC, Gumkle commented on message/forms.py
> +        fields = '__all__'
Oprócz kilku pól

2019-11-12 18:19 UTC, Gumkle commented on message/views.py
> +    form = MessageForm(request.POST or None, request.FILES or None)
Sprawdzenie czy post, sprawdzenie poprawności argumentów

2019-11-12 21:42 UTC, PatrykGrzegorek commented on lekarz/templates/message/outbox.html
> +<!DOCTYPE html>
Już myślę że poprawiłem wszystkie uwagi

2019-11-14 08:27 UTC, dwdzdc approved these changes

2019-11-14 08:27 UTC, merged